Add improved version

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,8 +1,17 @@
 #!/bin/bash
 
-set -e
+export NODE_ENV=test
 
 cd "$(dirname "$0")/.."
+
+teardown() {
+	script/teardown
+
+	exit ${1:0}
+}
+
+# On error teardown
+trap 'teardown $?' ERR
 
 echo "Tests started at..."
 date "+%H:%M:%S"
@@ -10,19 +19,29 @@ date "+%H:%M:%S"
 # Export some common variables
 export CI=true
 
-# Pick 
+# Pick CI context
 if [ ! -z "$DRONE_BUILD_NUMBER" ]; then
-	NOCONFLICT_CONTEXT=$DRONE_BUILD_NUMBER
+	export NOCONFLICT_CONTEXT=$DRONE_BUILD_NUMBER
 elif [ ! -z "$BUILD_ID" ]; then
-	NOCONFLICT_CONTEXT=$BUILD_ID
+	export NOCONFLICT_CONTEXT=$BUILD_ID
 elif [ ! -z "$TRAVIS_BUILD_ID" ]; then
-	NOCONFLICT_CONTEXT=$TRAVIS_BUILD_ID
+	export NOCONFLICT_CONTEXT=$TRAVIS_BUILD_ID
 else
-	NOCONFLICT_CONTEXT=ci-$RANDOM
+	export NOCONFLICT_CONTEXT=ci-$RANDOM
 fi
+
+# Bootstrap
+script/bootstrap
+
+# Prepare database and configs
+script/setup
 
 echo "Running tests ..."
 date "+%H:%M:%S"
 
-exec script/test
+# Run tests
+script/test
+
+# Cleanup environment
+teardown
 
